#!/usr/bin/env python
import argparse
import webbrowser
from httpreq import make_request
from searchreq import search_request
import urllib.parse

def main():
    parser = argparse.ArgumentParser(description="go2web CLI")
    parser.add_argument("-u", "--url", help="Make HTTP request to URL")
    parser.add_argument("-s", "--search", help="Search the term on Google")

    args = parser.parse_args()

    if args.url:
        print(f"Fetching URL: {args.url}")
        result = make_request(args.url)
        print(result)

    if args.search:
        print(f"Searching: {args.search}")
        results = search_request(args.search)
        for idx, (title, link) in enumerate(results, 1):
            print(f"{idx}. {title}\n {link}\n ")


        try:
            choice = int(input("What do you want to access?: "))
            if choice < 1 or choice > len(results):
                print("Invalid choice.")
                return
        except ValueError:
            print("Please enter a valid number")
            return
        link = results[choice - 1][1]

        if link.startswith("/l/") and "uddg=" in link:
            link = urllib.parse.parse_qs(urllib.parse.urlparse(link).query).get('uddg', [link])[0]
            link = urllib.parse.unquote(link)

        if link.startswith("/"):
            link = "https://duckduckgo.com" + link

        webbrowser.open_new(link)


if __name__ == "__main__":
    main()